version: '3'

services:
  strapi:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - '1337'  # Expose the port for internal networking
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - strapi
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
      - '443:443'  # For SSL support, if needed
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
